import { Inter } from "next/font/google";
import "./globals.css";
import { AuthProvider } from "@/context/AuthContext";
import ProtectedRoute from "@/components/ProtectedRoute";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import { AppContextProvider } from "@/context/AppContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "ThoughtLane",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <AuthProvider>
      <AppContextProvider>
        <html lang="en">
          <body className={inter.className}>
            <ProtectedRoute>
              <div className="min-h-screen px-4 pb-4 bg-dark-100 text-gray-100 flex flex-col justify-between">
                <Header />
                {children}
                <Footer />
              </div>
            </ProtectedRoute>
          </body>
        </html>
      </AppContextProvider>
    </AuthProvider>
  );
}
